### ISSUE TITLE
Delete empty lines between bullet points

### ISSUE THREAD

**Issue by qktsao** [Master-of-Business-Analytics/Web_page_repository#10]
@kemjika I added a style.css file so that now there is going to be 20px after each paragraph. However, this also means that if you have an empty line between two bullet points, they will be identified as separate paragraphs. Could you make sure to delete those empty lines in your Jupytor Notebook, Markdown, and RMarkdown? For example:

https://github.com/Master-of-Business-Analytics/Web_page_repository/blob/01a1bc7882e47a4ace4374a1e5557cc8bfffedc3/inventory_management.Rmd#L64-L84

**Comment by kemjika** [comment]
ok

**Comment by qktsao** [comment]
Hey sorry could you make the changes before closing the issue? Thanks!
